### ISSUE TITLE
Assign Prosody violations

### ISSUE THREAD

**Issue by clairemoorecantwell** [clairemoorecantwell/GSR_Learning#9]
HL roots should take single-syllable suffixes, -a, -ga, -i, etc.
LL and H roots should take two-syllable suffixes, -ia/-ina/-Cia, -aga, etc

HH roots, and trisyllabic roots never violate Prosody

**Comment by juliazaborna** [comment]
Works with -a, -ina;
Need to add -ga, -aga;
Could be used to analyze the -ina/a distribution in general.

**Comment by juliazaborna** [comment]
Added -ga/aga.
Can do the following now:
HL roots should take single-syllable suffixes, -a, -ga, -i, etc.
LL and H roots should take two-syllable suffixes, -ia/-ina/-Cia, -aga, etc

HH roots, and trisyllabic roots never violate Prosody
